# =========================
# Configuration Logic
# =========================

import os
from pathlib import Path

class Config:
    """Base config"""

    # Flask settings
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'vinylfy-secret-key-change-me'
    DEBUG = os.environ.get('FLASK_DEBUG', 'False').lower() == 'true'
    MAX_FILE_SIZE = int(os.environ.get('MAX_UPLOAD_SIZE', '25'))
    PROCESSED_FILES_TTL_HOURS = float(os.environ.get('FILE_TTL_HOURS', '1'))

    # File Upload Settings
    MAX_CONTENT_LENGTH = MAX_FILE_SIZE * 1024 * 1024 # Default 25MB
    UPLOAD_FOLDER = Path('/tmp/vinylfy/uploads')
    PROCESSED_FILES_DIR = Path('/tmp/vinylfy/processed')
    # PROCESSED_FILES_TTL_HOURS removed (duplicate)
    ALLOWED_EXTENSIONS = {'wav', 'mp3', 'flac', 'ogg', 'm4a', 'aac'}
    ALLOWED_OUTPUT_FORMATS = {'wav', 'mp3', 'aac', 'flac', 'ogg'}

    # Audio Processing Settings
    DEFAULT_SAMPLE_RATE = 44100
    OUTPUT_FORMAT = 'wav'
    OUTPUT_SAMPLE_WIDTH = 2 # 16-bit audio 

    # CORS SETTINGS
    CORS_ORIGINS =  os.environ.get('CORS_ORIGINS', '*').split(',')

    # Vinyl Effect Presets
    PRESETS = {
        # The A's recommended settings
        'AJW Recommended': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.018,
            'pop_intensity': 0.86,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0019,
            'harmonic_distortion': True,
            'distortion_amount': 0.34,
            'stereo_reduction': True,
            'stereo_width': 0.70,
            'bass': 0.4,
            'mid': 1.7,
            'treble': 1.7,
            'hpf_enabled': True,
            'hpf_cutoff': 120,
            'lpf_enabled': True,
            'lpf_cutoff': 15000,
        },
        '1920\'s Jazz': {
            'frequency_response': False,
            'surface_noise': True,
            'noise_intensity': 0.095,
            'pop_intensity': 0.9,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.009,
            'harmonic_distortion': True,
            'distortion_amount': 0.85,
            'stereo_reduction': True,
            'stereo_width': 0.0,
            'bass': -5.0,
            'mid': 5.0,
            'treble': -5.0,
            'hpf_enabled': True,
            'hpf_cutoff': 250,
            'lpf_enabled': True,
            'lpf_cutoff': 3500,
        },
        '1930\'s Swing': {
            'frequency_response': False,
            'surface_noise': True,
            'noise_intensity': 0.085,
            'pop_intensity': 0.75,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.009,
            'harmonic_distortion': True,
            'distortion_amount': 0.7,
            'stereo_reduction': True,
            'stereo_width': 0.0,
            'bass': -4.0,
            'mid': 4.0,
            'treble': -4.0,
            'hpf_enabled': True,
            'hpf_cutoff': 150,
            'lpf_enabled': True,
            'lpf_cutoff': 5000,
        },
        '1940\'s Big Band': {
            'frequency_response': False,
            'surface_noise': True,
            'noise_intensity': 0.075,
            'pop_intensity': 0.65,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.006,
            'harmonic_distortion': True,
            'distortion_amount': 0.6,
            'stereo_reduction': True,
            'stereo_width': 0.0,
            'bass': -2.0,
            'mid': 3.0,
            'treble': -3.0,
            'hpf_enabled': True,
            'hpf_cutoff': 100,
            'lpf_enabled': True,
            'lpf_cutoff': 8000,
        },
        '1950\'s Rock & Roll': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.055,
            'pop_intensity': 0.55,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.004,
            'harmonic_distortion': True,
            'distortion_amount': 0.5,
            'stereo_reduction': True,
            'stereo_width': 0.0,
            'bass': 1.0,
            'mid': 2.0,
            'treble': -1.0,
            'hpf_enabled': True,
            'hpf_cutoff': 60,
            'lpf_enabled': True,
            'lpf_cutoff': 10000,
        },
        '1950\'s Rhythm & Blues': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.055,
            'pop_intensity': 0.5,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0035,
            'harmonic_distortion': True,
            'distortion_amount': 0.55,
            'stereo_reduction': True,
            'stereo_width': 0.0,
            'bass': 2.0,
            'mid': 2.0,
            'treble': -2.0,
            'hpf_enabled': True,
            'hpf_cutoff': 50,
            'lpf_enabled': True,
            'lpf_cutoff': 9000,
        },
        '1960\'s Pop': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.045,
            'pop_intensity': 0.35,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.003,
            'harmonic_distortion': True,
            'distortion_amount': 0.35,
            'stereo_reduction': True,
            'stereo_width': 0.6,
            'bass': -1.0,
            'mid': 2.0,
            'treble': 2.0,
            'hpf_enabled': True,
            'hpf_cutoff': 40,
            'lpf_enabled': True,
            'lpf_cutoff': 14000,
        },
        '1960\'s Psychedelic': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.04,
            'pop_intensity': 0.4,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0045,
            'harmonic_distortion': True,
            'distortion_amount': 0.45,
            'stereo_reduction': True,
            'stereo_width': 0.9,
            'bass': 1.0,
            'mid': 1.0,
            'treble': 1.0,
            'hpf_enabled': True,
            'hpf_cutoff': 30,
            'lpf_enabled': True,
            'lpf_cutoff': 15000,
        },
        '1970\'s Rock': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.03,
            'pop_intensity': 0.2,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.002,
            'harmonic_distortion': True,
            'distortion_amount': 0.25,
            'stereo_reduction': True,
            'stereo_width': 0.95,
            'bass': 2.0,
            'mid': 0.0,
            'treble': 1.0,
            'hpf_enabled': True,
            'hpf_cutoff': 30,
            'lpf_enabled': True,
            'lpf_cutoff': 18000,
        },
        '1970\'s Disco': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.025,
            'pop_intensity': 0.1,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.001,
            'harmonic_distortion': True,
            'distortion_amount': 0.15,
            'stereo_reduction': True,
            'stereo_width': 1.0,
            'bass': 4.0,
            'mid': -1.0,
            'treble': 3.0,
            'hpf_enabled': True,
            'hpf_cutoff': 20,
            'lpf_enabled': True,
            'lpf_cutoff': 20000,
        },
        '1970\'s Funk': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.035,
            'pop_intensity': 0.25,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0015,
            'harmonic_distortion': True,
            'distortion_amount': 0.3,
            'stereo_reduction': True,
            'stereo_width': 0.95,
            'bass': 3.0,
            'mid': 1.0,
            'treble': 2.0,
            'hpf_enabled': True,
            'hpf_cutoff': 20,
            'lpf_enabled': True,
            'lpf_cutoff': 19000,
        },
        '1980\'s New Wave': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.02,
            'pop_intensity': 0.15,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.001,
            'harmonic_distortion': True,
            'distortion_amount': 0.1,
            'stereo_reduction': True,
            'stereo_width': 1.0,
            'bass': -1.0,
            'mid': 1.0,
            'treble': 4.0,
            'hpf_enabled': True,
            'hpf_cutoff': 40,
            'lpf_enabled': True,
            'lpf_cutoff': 20000,
        },
        '1980\'s Metal': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.035,
            'pop_intensity': 0.3,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.001,
            'harmonic_distortion': True,
            'distortion_amount': 0.45,
            'stereo_reduction': True,
            'stereo_width': 0.9,
            'bass': -1.0,
            'mid': -2.0,
            'treble': 3.0,
            'hpf_enabled': True,
            'hpf_cutoff': 40,
            'lpf_enabled': True,
            'lpf_cutoff': 18000,
        },
        '1990\'s Alternative': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.05,
            'pop_intensity': 0.35,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.002,
            'harmonic_distortion': True,
            'distortion_amount': 0.4,
            'stereo_reduction': True,
            'stereo_width': 0.85,
            'bass': 2.0,
            'mid': -1.0,
            'treble': 1.0,
            'hpf_enabled': True,
            'hpf_cutoff': 30,
            'lpf_enabled': True,
            'lpf_cutoff': 19000,
        },
        '1990\'s Hip-Hop': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.045,
            'pop_intensity': 0.4,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0005,
            'harmonic_distortion': True,
            'distortion_amount': 0.3,
            'stereo_reduction': True,
            'stereo_width': 0.8,
            'bass': 5.0,
            'mid': 0.0,
            'treble': 1.0,
            'hpf_enabled': True,
            'hpf_cutoff': 20,
            'lpf_enabled': True,
            'lpf_cutoff': 18000,
        },
        '2000\'s Pop': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.04,
            'pop_intensity': 0.2,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.001,
            'harmonic_distortion': True,
            'distortion_amount': 0.2,
            'stereo_reduction': True,
            'stereo_width': 0.95,
            'bass': 3.0,
            'mid': 1.0,
            'treble': 4.0,
            'hpf_enabled': True,
            'hpf_cutoff': 20,
            'lpf_enabled': True,
            'lpf_cutoff': 20000,
        },
        '2000\'s Indie': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.055,
            'pop_intensity': 0.3,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0025,
            'harmonic_distortion': True,
            'distortion_amount': 0.5,
            'stereo_reduction': True,
            'stereo_width': 0.9,
            'bass': 1.0,
            'mid': 3.0,
            'treble': -1.0,
            'hpf_enabled': True,
            'hpf_cutoff': 40,
            'lpf_enabled': True,
            'lpf_cutoff': 16000,
        },
        '2010\'s Pop': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.002,
            'pop_intensity': 0.1,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.001,
            'harmonic_distortion': True,
            'distortion_amount': 0.1,
            'stereo_reduction': True,
            'stereo_width': 1.0,
            'bass': 3.0,
            'mid': 0.0,
            'treble': 5.0,
            'hpf_enabled': True,
            'hpf_cutoff': 20,
            'lpf_enabled': True,
            'lpf_cutoff': 20000,
        },
        '2010\'s Electronic': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.0015,
            'pop_intensity': 0.05,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0005,
            'harmonic_distortion': True,
            'distortion_amount': 0.05,
            'stereo_reduction': True,
            'stereo_width': 0.85,
            'bass': 5.0,
            'mid': -2.0,
            'treble': 4.0,
            'hpf_enabled': True,
            'hpf_cutoff': 15,
            'lpf_enabled': True,
            'lpf_cutoff': 20000,
        },
        '2020\'s Modern Vinyl': {
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.005,
            'pop_intensity': 0.01,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.0002,
            'harmonic_distortion': True,
            'distortion_amount': 0.02,
            'stereo_reduction': True,
            'stereo_width': 1.0,
            'bass': 1.0,
            'mid': 0.0,
            'treble': 1.0,
            'hpf_enabled': True,
            'hpf_cutoff': 20,
            'lpf_enabled': True,
            'lpf_cutoff': 20000,
        },
        'custom': {
            # Custom presets - all values come from user through web interface
            # This is template to show all presets
            'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.02,
            'pop_intensity': 0.6,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.001,
            'harmonic_distortion': True,
            'distortion_amount': 0.15,
            'stereo_reduction': True,
            'stereo_width': 0.0,
            'bass': 0.0,
            'mid': 0.0,
            'treble': 0.0,
            'hpf_enabled': False,
            'hpf_cutoff': 30,
            'lpf_enabled': False,
            'lpf_cutoff': 20000,
        },
    }

    # Default settings for audio processing
    DEFAULT_SETTINGS = {
        'frequency_response': True,
            'surface_noise': True,
            'noise_intensity': 0.02,
            'pop_intensity': 0.6,
            'wow_flutter': True,
            'wow_flutter_intensity': 0.001,
            'harmonic_distortion': True,
            'distortion_amount': 0.15,
            'stereo_reduction': True,
            'stereo_width': 0.7,
            'bass': 0.0,
            'mid': 0.0,
            'treble': 0.0,
            'hpf_enabled': False,
            'hpf_cutoff': 30,
            'lpf_enabled': False,
            'lpf_cutoff': 15000,
    }

    @staticmethod
    def init_app(app):
        """Initialize app config"""
        Config.UPLOAD_FOLDER.mkdir(parents=True, exist_ok=True)
        Config.PROCESSED_FILES_DIR.mkdir(parents=True, exist_ok=True)

class DevelopmentConfig(Config):
    """Development config"""
    DEBUG = True
    TESTING = False

class ProductionConfig(Config):
    """Production Config"""
    DEBUG = False
    TESTING = False

class TestingConfig(Config):
    """Testing Config"""
    DEBUG = True
    TESTING = True

# Configuration directory
config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': DevelopmentConfig
}
